INSERT INTO LIMPIADOR (ID_EMPLEADO)
VALUES (1);
INSERT INTO LIMPIADOR (ID_EMPLEADO)
VALUES (2);
INSERT INTO LIMPIADOR (ID_EMPLEADO)
VALUES (3);
INSERT INTO LIMPIADOR (ID_EMPLEADO)
VALUES (4);
INSERT INTO LIMPIADOR (ID_EMPLEADO)
VALUES (5);
