INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (51,7,6);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (52,4,11);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (53,7,11);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (54,5,6);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (55,2,12);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (56,2,8);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (57,5,14);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (58,3,8);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (59,6,11);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (60,4,6);
