INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (61,3,98);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (62,6,72);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (63,5,66);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (64,1,100);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (65,3,92);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (66,3,101);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (67,4,89);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (68,5,69);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (69,3,87);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (70,3,80);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (71,1,82);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (72,5,101);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (73,7,68);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (74,6,72);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (75,6,76);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (76,2,75);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (77,4,98);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (78,2,95);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (79,5,91);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (80,6,71);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (81,4,82);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (82,4,81);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (83,6,101);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (84,6,79);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (85,2,75);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (86,3,95);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (87,4,68);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (88,4,85);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (89,4,74);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (90,5,85);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (91,3,66);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (92,4,80);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (93,3,102);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (94,2,74);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (95,1,77);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (96,4,100);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (97,4,105);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (98,4,98);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (99,1,91);
INSERT INTO RUTINA (ID_SERVICIO,DIAS_SEMANA,ID_EMPLEADO)
VALUES (100,2,82);
