INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (11,"VARIADA",61);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (12,"VEGANA",42);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (13,"PROTEICA",56);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (14,"CALORICA",57);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (15,"VEGANA",54);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (16,"VEGANA",54);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (17,"VEGANA",30);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (18,"VARIADA",39);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (19,"VEGANA",60);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (20,"VEGANA",38);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (21,"VARIADA",65);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (22,"CALORICA",62);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (23,"PROTEICA",30);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (24,"VEGANA",36);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (25,"MEDITERRANEA",46);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (26,"VEGANA",42);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (27,"VARIADA",47);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (28,"VEGANA",46);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (29,"CALORICA",53);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (30,"VARIADA",37);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (31,"CALORICA",44);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (32,"VEGANA",49);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (33,"MEDITERRANEA",58);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (34,"VEGANA",32);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (35,"CALORICA",62);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (36,"MEDITERRANEA",40);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (37,"VARIADA",42);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (38,"CALORICA",56);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (39,"CALORICA",47);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (40,"VEGANA",54);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (41,"VEGANA",28);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (42,"MEDITERRANEA",30);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (43,"PROTEICA",31);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (44,"PROTEICA",36);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (45,"PROTEICA",47);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (46,"CALORICA",45);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (47,"MEDITERRANEA",49);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (48,"VEGANA",30);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (49,"VEGANA",61);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (50,"VEGANA",52);
