INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (1,"PROTEICA",22);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (2,"VEGANA",17);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (3,"VEGANA",16);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (4,"MEDITERRANEA",19);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (5,"VARIADA",20);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (6,"VEGANA",20);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (7,"MEDITERRANEA",25);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (8,"PROTEICA",19);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (9,"VEGANA",21);
INSERT INTO DIETA (ID_SERVICIO,TIPO_DIETA,ID_EMPLEADO)
VALUES (10,"VARIADA",24);
