INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (1,"MULTIFUNCIONAL",160,2);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (2,"SENTADILLA",61,4);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (3,"SENTADILLA",240,2);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (4,"MANCUERNA",56,3);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (5,"MANCUERNA",103,2);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (6,"SENTADILLA",176,4);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (7,"PRENSA",278,2);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (8,"PRENSA",293,5);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (9,"MANCUERNA",280,3);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (10,"MULTIFUNCIONAL",77,2);
