INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (11,"MANCUERNA",200,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (12,"POLEA",50,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (13,"SENTADILLA",92,137);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (14,"SENTADILLA",185,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (15,"MULTIFUNCIONAL",91,148);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (16,"SENTADILLA",62,112);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (17,"SENTADILLA",131,123);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (18,"MANCUERNA",244,137);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (19,"MULTIESTACION",170,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (20,"SENTADILLA",10,148);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (21,"POLEA",104,139);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (22,"SENTADILLA",155,115);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (23,"MANCUERNA",9,146);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (24,"MULTIESTACION",36,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (25,"PRENSA",203,126);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (26,"MULTIFUNCIONAL",166,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (27,"MULTIESTACION",147,111);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (28,"POLEA",103,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (29,"MANCUERNA",258,139);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (30,"PRENSA",208,148);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (31,"MULTIFUNCIONAL",235,140);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (32,"MANCUERNA",32,108);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (33,"PRENSA",219,142);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (34,"MULTIFUNCIONAL",275,108);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (35,"MULTIFUNCIONAL",7,147);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (36,"MANCUERNA",220,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (37,"MULTIFUNCIONAL",17,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (38,"SENTADILLA",193,138);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (39,"POLEA",89,114);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (40,"SENTADILLA",193,142);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (41,"MULTIESTACION",200,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (42,"MULTIESTACION",166,117);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (43,"POLEA",206,139);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (44,"POLEA",69,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (45,"MULTIFUNCIONAL",81,112);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (46,"POLEA",63,119);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (47,"MULTIFUNCIONAL",64,143);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (48,"POLEA",290,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (49,"MULTIFUNCIONAL",46,125);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (50,"MULTIFUNCIONAL",115,112);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (51,"MANCUERNA",290,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (52,"MANCUERNA",95,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (53,"MULTIESTACION",156,114);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (54,"MANCUERNA",179,109);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (55,"MULTIFUNCIONAL",217,142);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (56,"PRENSA",197,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (57,"SENTADILLA",192,126);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (58,"PRENSA",236,138);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (59,"POLEA",205,147);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (60,"POLEA",35,126);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (61,"MULTIESTACION",194,140);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (62,"MULTIFUNCIONAL",168,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (63,"MANCUERNA",269,116);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (64,"POLEA",289,109);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (65,"POLEA",296,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (66,"MULTIFUNCIONAL",257,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (67,"MULTIESTACION",97,143);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (68,"POLEA",168,111);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (69,"MULTIESTACION",77,116);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (70,"MULTIESTACION",84,109);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (71,"MULTIESTACION",298,139);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (72,"SENTADILLA",148,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (73,"POLEA",43,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (74,"PRENSA",140,144);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (75,"MULTIESTACION",16,138);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (76,"MULTIESTACION",299,122);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (77,"PRENSA",64,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (78,"POLEA",153,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (79,"PRENSA",128,147);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (80,"MULTIFUNCIONAL",180,106);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (81,"POLEA",226,119);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (82,"PRENSA",130,127);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (83,"MANCUERNA",197,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (84,"MULTIFUNCIONAL",227,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (85,"MULTIESTACION",169,107);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (86,"MANCUERNA",259,145);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (87,"PRENSA",96,148);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (88,"SENTADILLA",202,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (89,"MULTIFUNCIONAL",226,133);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (90,"MULTIESTACION",212,112);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (91,"MULTIFUNCIONAL",131,143);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (92,"POLEA",22,131);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (93,"PRENSA",97,142);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (94,"MULTIFUNCIONAL",29,114);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (95,"SENTADILLA",246,133);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (96,"MULTIESTACION",52,134);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (97,"MANCUERNA",228,143);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (98,"POLEA",155,141);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (99,"MANCUERNA",250,140);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (100,"PRENSA",245,119);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (101,"MANCUERNA",18,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (102,"PRENSA",56,115);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (103,"POLEA",67,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (104,"MANCUERNA",49,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (105,"POLEA",292,146);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (106,"MANCUERNA",273,115);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (107,"MULTIESTACION",31,115);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (108,"MANCUERNA",194,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (109,"MULTIFUNCIONAL",151,123);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (110,"PRENSA",195,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (111,"MULTIESTACION",237,150);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (112,"MULTIESTACION",191,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (113,"PRENSA",199,128);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (114,"SENTADILLA",274,108);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (115,"POLEA",97,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (116,"MULTIFUNCIONAL",72,141);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (117,"MULTIFUNCIONAL",175,131);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (118,"POLEA",136,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (119,"MULTIESTACION",90,128);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (120,"MULTIESTACION",83,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (121,"MULTIESTACION",212,111);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (122,"MULTIFUNCIONAL",197,126);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (123,"PRENSA",102,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (124,"MULTIESTACION",71,111);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (125,"MANCUERNA",54,139);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (126,"MULTIFUNCIONAL",39,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (127,"MANCUERNA",26,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (128,"MULTIFUNCIONAL",189,144);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (129,"MULTIFUNCIONAL",75,126);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (130,"MANCUERNA",294,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (131,"MULTIESTACION",112,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (132,"MULTIESTACION",58,113);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (133,"MULTIFUNCIONAL",115,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (134,"MULTIESTACION",135,134);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (135,"PRENSA",192,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (136,"PRENSA",94,118);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (137,"MULTIESTACION",52,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (138,"PRENSA",163,132);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (139,"MULTIFUNCIONAL",258,128);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (140,"POLEA",182,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (141,"MULTIFUNCIONAL",151,144);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (142,"SENTADILLA",99,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (143,"MULTIESTACION",141,114);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (144,"SENTADILLA",29,135);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (145,"MULTIESTACION",6,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (146,"SENTADILLA",126,143);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (147,"MULTIESTACION",279,114);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (148,"PRENSA",53,110);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (149,"SENTADILLA",119,109);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (150,"MANCUERNA",228,109);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (151,"MULTIESTACION",135,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (152,"PRENSA",291,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (153,"PRENSA",68,122);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (154,"MULTIFUNCIONAL",169,125);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (155,"POLEA",24,149);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (156,"MULTIFUNCIONAL",225,130);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (157,"MULTIESTACION",32,123);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (158,"POLEA",89,119);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (159,"MULTIESTACION",17,145);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (160,"MULTIFUNCIONAL",52,150);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (161,"PRENSA",39,123);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (162,"MULTIESTACION",288,120);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (163,"MANCUERNA",65,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (164,"MULTIESTACION",92,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (165,"POLEA",199,124);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (166,"MANCUERNA",286,119);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (167,"SENTADILLA",208,136);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (168,"MANCUERNA",293,121);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (169,"POLEA",234,129);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (170,"POLEA",164,128);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (171,"PRENSA",280,135);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (172,"PRENSA",197,117);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (173,"MULTIESTACION",99,127);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (174,"PRENSA",288,133);
INSERT INTO MAQUINA (ID_MAQUINA,TIPO,PESO_INICIAL,ID_EMPLEADO)
VALUES (175,"POLEA",279,143);
