INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (26);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (27);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (28);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (29);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (30);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (31);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (32);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (33);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (34);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (35);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (36);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (37);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (38);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (39);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (40);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (41);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (42);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (43);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (44);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (45);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (46);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (47);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (48);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (49);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (50);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (51);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (52);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (53);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (54);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (55);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (56);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (57);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (58);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (59);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (60);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (61);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (62);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (63);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (64);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (65);
