INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (16);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (17);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (18);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (19);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (20);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (21);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (22);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (23);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (24);
INSERT INTO NUTRICIONISTA (ID_EMPLEADO)
VALUES (25);
