INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (123,1);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (103,2);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (80,3);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (61,4);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (115,5);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (2,6);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (20,7);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (36,8);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (88,9);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (172,10);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (192,11);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (138,12);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (73,13);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (127,14);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (111,15);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (141,16);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (96,17);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (149,18);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (106,19);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (18,20);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (22,21);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (42,22);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (30,23);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (162,24);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (103,25);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (181,26);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (231,27);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (147,28);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (165,29);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (93,30);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (185,31);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (55,32);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (46,33);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (181,34);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (116,35);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (31,36);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (137,37);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (138,38);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (53,39);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (246,40);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (177,41);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (175,42);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (48,43);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (2,44);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (1,45);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (231,46);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (173,47);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (162,48);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (141,49);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (41,50);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (163,51);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (96,52);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (246,53);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (161,54);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (63,55);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (15,56);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (44,57);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (128,58);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (170,59);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (231,60);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (124,61);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (153,62);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (238,63);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (76,64);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (210,65);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (139,66);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (100,67);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (54,68);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (63,69);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (113,70);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (214,71);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (40,72);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (20,73);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (177,74);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (38,75);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (43,76);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (18,77);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (16,78);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (212,79);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (22,80);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (32,81);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (64,82);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (203,83);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (35,84);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (46,85);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (95,86);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (109,87);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (1,88);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (134,89);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (190,90);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (24,91);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (31,92);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (127,93);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (20,94);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (190,95);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (163,96);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (112,97);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (72,98);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (237,99);
INSERT INTO USUARIO_CONTRATA_SERVICIO (ID_USUARIO,ID_SERVICIO)
VALUES (105,100);
