INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (66);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (67);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (68);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (69);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (70);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (71);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (72);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (73);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (74);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (75);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (76);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (77);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (78);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (79);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (80);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (81);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (82);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (83);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (84);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (85);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (86);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (87);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (88);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (89);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (90);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (91);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (92);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (93);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (94);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (95);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (96);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (97);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (98);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (99);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (100);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (101);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (102);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (103);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (104);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (105);
