INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (6);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (7);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (8);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (9);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (10);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (11);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (12);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (13);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (14);
INSERT INTO MONITOR (ID_EMPLEADO)
VALUES (15);
